<?php
/**
 * Copyright © 2016 Mozg. All rights reserved.
 * See LICENSE.txt for license details.
 */

/*dump($this->getData());
dump(get_class_methods(get_class($this)));
dump(get_class_vars(get_class($this)));*/

?>

<!-- <?php echo get_class($this) ?> -->

<script type="text/javascript">
console.log('<?php echo get_class($this) ?>');
</script>

<?php if ($this->isCurrentMethod()): ?>

	<div class="redecard-checkout-onepage-success">

		<?php if ($this->isBoletoPayment()): ?>
		<div class="payment-url">
		    <?php echo Mage::helper('mozg_redecard')->__('<a href="%s">Click here to download the Boleto payment PDF</a>', $this->getPaymentUrl()) ?>
		</div>
		<?php endif; ?>

		<?php if ($this->isEletronicTransferPayment()): ?>
		<div class="payment-url">
		    <?php echo Mage::helper('mozg_redecard')->__('<a href="%s">Click here to process the EletronicTransfer payment</a>', $this->getPaymentUrl()) ?>
		</div>
		<?php endif; ?>

	</div>

<?php endif; ?>

<!-- / <?php echo get_class($this) ?> -->